### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by Winter-is-comingXK** [lkeme/BiliHelper-personal#149]
[2021-12-24 02:57:04] BH.INFO: (ActivityLottery) => 活动抽奖任务分配完成 0 个任务待执行 [] []
[2021-12-24 02:57:04] BH.INFO: (DailyTask) => 正在检查每日任务... [] []
[2021-12-24 02:57:04] BH.INFO: (DailyTask) => 检查任务「每日签到」... [] []
[2021-12-24 02:57:04] BH.NOTICE: (DailyTask) => 签到成功: 3000点用户经验,2根辣条 [] []
[2021-12-24 02:57:05] BH.WARNING: (Silver2Coin) => [APP] 银瓜子兑换硬币: 银瓜子余额不足 [] []
[2021-12-24 02:57:06] BH.WARNING: (Silver2Coin) => [PC] 银瓜子兑换硬币: 银瓜子余额不足 [] []
[2021-12-24 02:57:06] BH.NOTICE: (GroupSignIn) => 在应援团{皖团b站小分队②}中签到成功,增加{10点}亲密度 [] []
[2021-12-24 02:57:06] BH.NOTICE: (XliveHeartBeat) => 已在直播间 21686237 连续观看了 9 分钟 [] []
[2021-12-24 02:57:06] BH.INFO: (CapsuleLottery) => 扭蛋抽奖任务分配完成 0 个任务待执行 [] []
[2021-12-24 02:57:06] BH.INFO: (PolishTheMedal) => 开始点亮直播间@22412808的勋章 [] []
[2021-12-24 02:57:06] BH.NOTICE: (PolishTheMedal) => 在直播间@22412808发送点亮弹幕成功 [] []
[2021-12-24 02:57:06] BH.INFO: (VipPrivilege) => 获取大会员权益列表成功 [] []
[2021-12-24 02:57:07] BH.NOTICE: (VipPrivilege) => 大会员权益 B币劵 领取成功 [] []
[2021-12-24 02:57:07] BH.NOTICE: (VipPrivilege) => 大会员权益 会员购优惠券 领取成功 [] []
PHP Warning:  Undefined array key 3 in /app/BiliHelper-personal-master/src/plugin/VipPrivilege.php on line 70

Warning: Undefined array key 3 in /app/BiliHelper-personal-master/src/plugin/VipPrivilege.php on line 70
[2021-12-24 02:57:07] BH.NOTICE: (VipPrivilege) => 大会员权益  领取成功 [] []
PHP Fatal error:  Uncaught Error: Call to undefined function pcntl_signal_dispatch() in /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop/NativeDriver.php:161
Stack trace:
#0 /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#1 /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#2 /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#3 /app/BiliHelper-personal-master/src/core/App.php(171): Amp\Loop::run()
#4 /app/BiliHelper-personal-master/src/core/App.php(209): BiliHelper\Core\App->loop_m()
#5 /app/BiliHelper-personal-master/index.php(17): BiliHelper\Core\App->start()
#6 {main}
  thrown in /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop/NativeDriver.php on line 161

Fatal error: Uncaught Error: Call to undefined function pcntl_signal_dispatch() in /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop/NativeDriver.php:161
Stack trace:
#0 /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#1 /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#2 /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#3 /app/BiliHelper-personal-master/src/core/App.php(171): Amp\Loop::run()
#4 /app/BiliHelper-personal-master/src/core/App.php(209): BiliHelper\Core\App->loop_m()
#5 /app/BiliHelper-personal-master/index.php(17): BiliHelper\Core\App->start()
#6 {main}
  thrown in /app/BiliHelper-personal-master/vendor/amphp/amp/lib/Loop/NativeDriver.php on line 161

**Comment by lkeme** [comment]
[enable pcntl_signal_dispatch()](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&ch=&tn=98012088_oem_dg&bar=&wd=%E8%A7%A3%E9%99%A4%E7%A6%81%E7%94%A8%E5%87%BD%E6%95%B0+pcntl_signal_dispatch%28%29&oq=%25E8%25A7%25A3%25E9%2599%25A4%25E7%25A6%2581%25E7%2594%25A8%25E5%2587%25BD%25E6%2595%25B0%2520pcntl_signal_dispatch%28%29&rsv_pq=d3f702850000fd05&rsv_t=826cMSDiIcEhqE2P%2BieO%2FkHDLP6cWDsvb%2Bws4JUNgWMQqyeemvzWNFjn2wCcOhr6xnKBb2Pn&rqlang=cn&rsv_enter=0&rsv_btype=t&rsv_dl=tb)
