### ISSUE TITLE
Error:  Path cannot be empty in /home/poly/BiliHelper-personal/src/core/Curl.php

### ISSUE THREAD

**Issue by poly000** [lkeme/BiliHelper-personal#54]
```
PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /home/poly/BiliHelper-personal/src/core/Curl.php:156
Stack trace:
#0 /home/poly/BiliHelper-personal/src/core/Curl.php(156): file_get_contents()
#1 /home/poly/BiliHelper-personal/src/core/Log.php(108): BiliHelper\Core\Curl::request()
#2 /home/poly/BiliHelper-personal/src/core/Log.php(74): BiliHelper\Core\Log::callback()
#3 /home/poly/BiliHelper-personal/src/core/Env.php(52): BiliHelper\Core\Log::info()
#4 /home/poly/BiliHelper-personal/src/core/App.php(25): BiliHelper\Core\Env->inspect_configure()
#5 /home/poly/BiliHelper-personal/index.php(17): BiliHelper\Core\App->__construct()
#6 {main}
  thrown in /home/poly/BiliHelper-personal/src/core/Curl.php on line 156

Fatal error: Uncaught ValueError: Path cannot be empty in /home/poly/BiliHelper-personal/src/core/Curl.php:156
Stack trace:
#0 /home/poly/BiliHelper-personal/src/core/Curl.php(156): file_get_contents()
#1 /home/poly/BiliHelper-personal/src/core/Log.php(108): BiliHelper\Core\Curl::request()
#2 /home/poly/BiliHelper-personal/src/core/Log.php(74): BiliHelper\Core\Log::callback()
#3 /home/poly/BiliHelper-personal/src/core/Env.php(52): BiliHelper\Core\Log::info()
#4 /home/poly/BiliHelper-personal/src/core/App.php(25): BiliHelper\Core\Env->inspect_configure()
#5 /home/poly/BiliHelper-personal/index.php(17): BiliHelper\Core\App->__construct()
#6 {main}

```

**Comment by lkeme** [comment]
php8.的问题，尚未兼容到，请使用php7.
